# frozen_string_literal: true

source 'https://rubygems.org'

# TODO:[@kig] support gemspec in a Gemfile

gem 'colored2'

group :test, :development do
  gem 'rake'
  gem 'relaxed-rubocop'
  gem 'rspec'
  gem 'rubocop'
  gem 'simplecov'
  gem 'simplecov-formatter-badge'
end
