# frozen_string_literal: true

source 'https://rubygems.org'

gemspec

#gem('colored2')
#
#group :test, :development do
#  gem('rake')
#  gem('relaxed-rubocop')
#  gem('rspec')
#  gem('rubocop', '>= 0.73')
#  gem('simplecov')
#  gem('simplecov-formatter-badge')
#end
