# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.7.1
    working_directory: /home/circleci/repo
    environment:
      HELLO_WORLD_PATH: /home/circleci/repo/ruby/gems/hello_world

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "ruby/gems/hello_world/Gemfile.lock" }}
      - run:
          name: Install Bundled Dependencies
          command: |
            cd ${HELLO_WORLD_PATH} && bundle install --jobs=4 --retry=3 --path vendor/bundle

      - save_cache:
          paths:
            - ${HELLO_WORLD_PATH}/vendor/bundle
          key: v1-dependencies-{{ checksum "${HELLO_WORLD_PATH}/Gemfile.lock" }}

      - run:
          name: Run Bundler
          command: |
            cd ${HELLO_WORLD_PATH} && bundle check || bundle install

      - run:
          name: Run RSpecs
          command: |
            cd ${HELLO_WORLD_PATH} && bundle exec rspec -p 2

  style:
    docker:
      - image: circleci/ruby:2.7.1
    working_directory: /home/circleci/repo
    environment:
      HELLO_WORLD_PATH: /home/circleci/repo/ruby/gems/hello_world

    steps:
      - checkout
      - run:
          name: " ✅   Run Ruby Style Check"
          command: |
            /usr/bin/env bash bin/ruby-check

      - run:
          name: " Check if GCC/CC are installed"
          command: |
            set +e
            which gcc
            which cc
            which cc1
            cc --version  || true
            cc1 --version || true
            gcc --version || true

  bazel:
    docker:
      - image: circleci/ruby:2.7.1
    working_directory: /home/circleci/repo
    environment:
      HELLO_WORLD_PATH: /home/circleci/repo/ruby/gems/hello_world
    steps:
      - checkout
      - run:
          name: " ✅   Run Setup"
          command: |
            /usr/bin/env bash bin/setup

      - run:
          name: " ✅   Run Bazel Commands & Build"
          command: |
            bazel query //...:all
            echo
            bazel build //...:all

      - run:
          name: " ✅    Run HelloWorld CLI via Bazel"
          command: |
            bazel run //ruby/gems/hello_world:cli spanish japanese turkish russian

      - run:
          name: " ✅   Run HelloWorld SPECS via Bazel"
          command: |
            bazel run //ruby/gems/hello_world:specs

      - run:
          name: " ✅   Build Sinatra App with Bazel"
          command: |
            bazel build //ruby/apps/hello-world-web:all

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - style
      - bazel
